config/routes.rb
Rails.application.routes.draw do
  root to: 'cars#index'
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  require 'open-uri'
  require 'zip'
  require 'csv'
  require 'pry'

  validates :vin, presence: true

  self.per_page = 25

  def self.download_zip(url='https://data.gov.ua/dataset/0ffd8b75-0628-48cc-952a-9302f9799ec0/resource/c5cb530d-0533-40be-b9ad-f03e06c94b10/download/tz_opendata_z01012021_po01122021.zip')
    download = URI.parse(url).open
    IO.copy_stream(download, "#{Rails.public_path}/zip/data.zip")
  end

  def self.extract_zip(file, destination)
    FileUtils.mkdir_p(destination)

    Zip::File.open(file) do |zip_file|
      zip_file.each do |f|
        fpath = File.join(destination, f.name)
        zip_file.extract(f, fpath) unless File.exist?(fpath)
      end
    end
  end

  def self.unzip_csv
    extract_zip("#{Rails.public_path}/zip/data.zip", "#{Rails.public_path}/csv")
  end

  def self.update_from_csv(file="#{Rails.public_path}/csv/tz_opendata_z01012021_po01122021.csv")
    cars_data = CSV.read(file, headers: true, col_sep: ';')

    cars_data.each do |car|
      car_in_db = self.find_by(vin: car['VIN'])
      car_in_db.nil? ? create_car_record(car) : update_car_record(car_in_db, car)
    end
  end
  
  def self.create_car_record(car)
    self.create(
      person: car['PERSON'],
      reg_addr_koatuu: car['REG_ADDR_KOATUU'],
      oper_code: car['OPER_CODE'],
      oper_name: car['OPER_NAME'],
      d_reg: car['D_REG'],
      dep_code: car['DEP_CODE'],
      dep: car['DEP'],
      brand: car['BRAND'],
      model: car['MODEL'],
      vin: car['VIN'],
      make_year: car['MAKE_YEAR'],
      color: car['COLOR'],
      kind: car['KIND'],
      body: car['BODY'],
      purpose: car['PURPOSE'],
      fuel: car['FUEL'],
      capacity: car['CAPACITY'],
      own_weight: car['OWN_WEIGHT'],
      total_weight: car['TOTAL_WEIGHT'],
      n_reg_new: car['N_REG_NEW']
    )
  end
  
  def self.update_car_record(car_in_db, car)
    car_in_db.update_attributes(
      person: car['PERSON'],
      reg_addr_koatuu: car['REG_ADDR_KOATUU'],
      oper_code: car['OPER_CODE'],
      oper_name: car['OPER_NAME'],
      d_reg: car['D_REG'],
      dep_code: car['DEP_CODE'],
      dep: car['DEP'],
      brand: car['BRAND'],
      model: car['MODEL'],
      make_year: car['MAKE_YEAR'],
      color: car['COLOR'],
      kind: car['KIND'],
      body: car['BODY'],
      purpose: car['PURPOSE'],
      fuel: car['FUEL'],
      capacity: car['CAPACITY'],
      own_weight: car['OWN_WEIGHT'],
      total_weight: car['TOTAL_WEIGHT'],
      n_reg_new: car['N_REG_NEW']
    )
  end

  def self.search(search)
    if search.empty?
      self.all
    else
      self.where(vin: search)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.search(params[:search]).paginate(page: params[:page])
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(
        :vin,
        :person,
        :reg_addr_koatuu,
        :oper_code,
        :oper_name,
        :d_reg,
        :dep_code,
        :brand,
        :model,
        :make_year,
        :color,
        :kind,
        :body,
        :purpose,
        :fuel,
        :capacity,
        :own_weight,
        :total_weight,
        :n_reg_new,
        :search
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table border="1">
    <tbody>
    <%= render "form_field", form: form, row_title: 'VIN', row_data: :vin %>
    <%= render "form_field", form: form, row_title: 'Brand', row_data: :brand %>
    <%= render "form_field", form: form, row_title: 'Model', row_data: :model %>
    <%= render "form_field", form: form, row_title: 'Color', row_data: :color %>
    <%= render "form_field", form: form, row_title: 'Make Year', row_data: :make_year %>
    <%= render "form_field", form: form, row_title: 'Person', row_data: :person %>
    <%= render "form_field", form: form, row_title: 'Registration Address KOATUU', row_data: :reg_addr_koatuu %>
    <%= render "form_field", form: form, row_title: 'Operation Code', row_data: :oper_code %>
    <%= render "form_field", form: form, row_title: 'Operation Name', row_data: :oper_name %>
    <%= render "form_field", form: form, row_title: 'Date Of Registration', row_data: :d_reg %>
    <%= render "form_field", form: form, row_title: 'DEP Code', row_data: :dep_code %>
    <%= render "form_field", form: form, row_title: 'DEP', row_data: :dep %>
    <%= render "form_field", form: form, row_title: 'Kind', row_data: :kind %>
    <%= render "form_field", form: form, row_title: 'Body', row_data: :body %>
    <%= render "form_field", form: form, row_title: 'Purpose', row_data: :purpose %>
    <%= render "form_field", form: form, row_title: 'Fuel', row_data: :fuel %>
    <%= render "form_field", form: form, row_title: 'Capacity', row_data: :capacity %>
    <%= render "form_field", form: form, row_title: 'Own Weight', row_data: :own_weight %>
    <%= render "form_field", form: form, row_title: 'Total Weight', row_data: :total_weight %>
    <%= render "form_field", form: form, row_title: 'Number Of Registration', row_data: :n_reg_new %>
    </tbody>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/_form_field.html.erb
<tr>
  <td><h4><%= row_title %></h4></td>
  <td><%= form.text_field row_data %></td>
</tr>

app/views/cars/_search.html.erb
<%= form_tag(cars_path, method: :get) do %>
  <%= label_tag "Search by VIN code:" %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag "Search" %>
<% end %>

app/views/cars/_show_field.html.erb
<tr>
  <td><h4><%= row_title %></h4></td>
  <td><%= row_data %></td>
</tr>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>VIN Base</h1>

<div><%= render 'search' %></div>

<table border="1">
  <thead>
    <tr>
      <th>VIN</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Make Year</th>
      <th>Fuel</th>
      <th>Registration Number</th>
      <th>Operation Code</th>
      <th>Operation Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.vin %></td>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.make_year %></td>
        <td><%= car.fuel %></td>
        <td><%= car.n_reg_new %></td>
        <td><%= car.oper_code %></td>
        <td><%= car.oper_name %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @cars %>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Full Information</h1>

<table border="1">
  <tbody>
    <%= render "show_field", row_title: 'VIN', row_data: @car.vin %>
    <%= render "show_field", row_title: 'Brand', row_data: @car.brand %>
    <%= render "show_field", row_title: 'Model', row_data: @car.model %>
    <%= render "show_field", row_title: 'Color', row_data: @car.color %>
    <%= render "show_field", row_title: 'Make Year', row_data: @car.make_year %>
    <%= render "show_field", row_title: 'Person', row_data: @car.person %>
    <%= render "show_field", row_title: 'Registration Address KOATUU', row_data: @car.reg_addr_koatuu %>
    <%= render "show_field", row_title: 'Operation Code', row_data: @car.oper_code %>
    <%= render "show_field", row_title: 'Operation Name', row_data: @car.oper_name %>
    <%= render "show_field", row_title: 'Date Of Registration', row_data: @car.d_reg %>
    <%= render "show_field", row_title: 'DEP Code', row_data: @car.dep_code %>
    <%= render "show_field", row_title: 'DEP', row_data: @car.dep %>
    <%= render "show_field", row_title: 'Kind', row_data: @car.kind %>
    <%= render "show_field", row_title: 'Body', row_data: @car.body %>
    <%= render "show_field", row_title: 'Purpose', row_data: @car.purpose %>
    <%= render "show_field", row_title: 'Fuel', row_data: @car.fuel %>
    <%= render "show_field", row_title: 'Capacity', row_data: @car.capacity %>
    <%= render "show_field", row_title: 'Own Weight', row_data: @car.own_weight %>
    <%= render "show_field", row_title: 'Total Weight', row_data: @car.total_weight %>
    <%= render "show_field", row_title: 'Number Of Registration', row_data: @car.n_reg_new %>
  </tbody>
</table>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VinBase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>